from .admin import (generate_admin_all_invite_keyboard,
                    generate_admin_all_parameters_keyboard,
                    generate_admin_all_roles_keyboard,
                    generate_admin_all_users_keyboard,
                    generate_admin_create_parameter_choose_roles_keyboard,
                    generate_admin_create_parameter_choose_rule_keyboard,
                    generate_admin_create_parameter_norm_choose_keyboard,
                    generate_admin_edit_parameter_cancel_keyboard,
                    generate_admin_edit_parameter_keyboard,
                    generate_admin_edit_parameter_norm_choose_keyboard,
                    generate_admin_edit_parameter_roles_keyboard,
                    generate_admin_edit_parameter_rule_keyboard,
                    generate_admin_invite_cancel_keyboard,
                    generate_admin_invite_choose_roles_keyboard,
                    generate_admin_roles_keyboard,
                    generate_admin_start_keyboard,
                    generate_admin_to_all_users_keyboard,
                    generate_admin_to_main_keyboard,
                    generate_admin_to_parameter_keyboard,
                    generate_admin_to_user_keyboard,
                    generate_admin_user_cancel_keyboard,
                    generate_admin_user_edit_keyboard,
                    generate_admin_user_edit_role_keyboard,
                    generate_checkbox_keyboard,)

__all__ = ['generate_admin_all_invite_keyboard',
           'generate_admin_all_parameters_keyboard',
           'generate_admin_all_roles_keyboard',
           'generate_admin_all_users_keyboard',
           'generate_admin_create_parameter_choose_roles_keyboard',
           'generate_admin_create_parameter_choose_rule_keyboard',
           'generate_admin_create_parameter_norm_choose_keyboard',
           'generate_admin_edit_parameter_cancel_keyboard',
           'generate_admin_edit_parameter_keyboard',
           'generate_admin_edit_parameter_norm_choose_keyboard',
           'generate_admin_edit_parameter_roles_keyboard',
           'generate_admin_edit_parameter_rule_keyboard',
           'generate_admin_invite_cancel_keyboard',
           'generate_admin_invite_choose_roles_keyboard',
           'generate_admin_roles_keyboard', 'generate_admin_start_keyboard',
           'generate_admin_to_all_users_keyboard',
           'generate_admin_to_main_keyboard',
           'generate_admin_to_parameter_keyboard',
           'generate_admin_to_user_keyboard',
           'generate_admin_user_cancel_keyboard',
           'generate_admin_user_edit_keyboard',
           'generate_admin_user_edit_role_keyboard',
           'generate_checkbox_keyboard']
