from .admin import (generate_admin_all_parameters_keyboard,
                    generate_admin_all_roles_keyboard,
                    generate_admin_create_parameter_choose_roles_keyboard,
                    generate_admin_create_parameter_choose_rule_keyboard,
                    generate_admin_create_parameter_norm_choose_keyboard,
                    generate_admin_edit_parameter_cancel_keyboard,
                    generate_admin_edit_parameter_keyboard,
                    generate_admin_edit_parameter_norm_choose_keyboard,
                    generate_admin_edit_parameter_roles_keyboard,
                    generate_admin_edit_parameter_rule_keyboard,
                    generate_admin_invite_keyboard,
                    generate_admin_roles_invite_keyboard,
                    generate_admin_roles_keyboard,
                    generate_admin_start_keyboard,
                    generate_admin_to_main_keyboard,
                    generate_checkbox_keyboard,)

__all__ = ['generate_admin_all_parameters_keyboard',
           'generate_admin_all_roles_keyboard',
           'generate_admin_create_parameter_choose_roles_keyboard',
           'generate_admin_create_parameter_choose_rule_keyboard',
           'generate_admin_create_parameter_norm_choose_keyboard',
           'generate_admin_edit_parameter_cancel_keyboard',
           'generate_admin_edit_parameter_keyboard',
           'generate_admin_edit_parameter_norm_choose_keyboard',
           'generate_admin_edit_parameter_roles_keyboard',
           'generate_admin_edit_parameter_rule_keyboard',
           'generate_admin_invite_keyboard',
           'generate_admin_roles_invite_keyboard',
           'generate_admin_roles_keyboard', 'generate_admin_start_keyboard',
           'generate_admin_to_main_keyboard', 'generate_checkbox_keyboard']
