"""update parameter table

Revision ID: 4ed6e9f1eb48
Revises: e4cb9d5d04e2
Create Date: 2026-06-26 23:15:22.422947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ed6e9f1eb48'
down_revision: Union[str, Sequence[str], None] = 'e4cb9d5d04e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter', sa.Column('rule', sa.String(length=255), nullable=False))
    op.drop_column('survey_question', 'rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_question', sa.Column('rule', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('parameter', 'rule')
    # ### end Alembic commands ###
