"""add unique constraints

Revision ID: 77b847f6e675
Revises: 4ed6e9f1eb48
Create Date: 2026-06-27 00:24:58.680851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77b847f6e675'
down_revision: Union[str, Sequence[str], None] = '4ed6e9f1eb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer', ['parameter_id', 'daily_survey_id'])
    op.create_unique_constraint(None, 'daily_survey', ['survey_id', 'patient_id', 'start_date'])
    op.create_unique_constraint(None, 'patient_survey', ['patient_id', 'survey_id'])
    op.alter_column('survey_question', 'parameter_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('survey_question', 'survey_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_question', 'survey_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('survey_question', 'parameter_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'patient_survey', type_='unique')
    op.drop_constraint(None, 'daily_survey', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    # ### end Alembic commands ###
