"""add some

Revision ID: e4cb9d5d04e2
Revises: 70f762f93eb7
Create Date: 2026-06-26 03:35:52.184247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb9d5d04e2'
down_revision: Union[str, Sequence[str], None] = '70f762f93eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.add_column('parameter', sa.Column('code', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'parameter', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameter', type_='unique')
    op.drop_column('parameter', 'code')
    op.drop_column('invite', 'used_at')
    # ### end Alembic commands ###
